name: assetleaders.org
favicon: null
layout_spectrum: 0.29769
typography_spectrum: 0.33075
title: alp
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0082cf'
    - '#000000'
    - '#ffffff'
    - '#fd6500'
    - '#ffd600'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
